#' Sample from Concavex model posteriors
#' 
#' This function samples from posterior densities of concavex model parameters as well as transformations of parameters.
#' 
#' @param ccvx.mod  JAGS model file as specified by \link{ccvx_build_jags}
#' @param doses A vector of dose strengths, with placebo listed first
#' @param mu.hat A vector of parameter estimates for each of the doses
#' @param std.err A vector of standard errors for each of the doses
#' @param n.chains Number of chains used to for Gibbs sampling. Default is 4
#' @param gibbs.samples Number of samples to draw for each chain after burn in. Default is 5000
#' 
#' @return A list with the elements
#' \item{ccvx.mod}{The JAGS code used for Gibbs sampling as generated by \link{ccvx_build_jags}}
#' \item{jags.samples}{output containing Gibbs samples generated using rjags}
#' \item{coda.samples}{output containing coda samples for MCMC diagnostics}
#' \item{doses}{A vector of dose strengths, with placebo listed first}
#' \item{mu.hat}{A vector of parameter estimates for each of the doses}
#' \item{std.err}{A vector of standard errors for each of the doses}
#' 
#' @export
#' @examples 
#' ccvx.mod <- ccvx_build_jags()
#' ccvx.samples <- ccvx_fit(ccvx.mod, doses = 0:4, mu.hat = c(1, 20, 50, 60, 65), std.err = rep(10, 5))
#' ccvx_plot_fit(ccvx.samples)

ccvx_fit <- function(ccvx.mod, doses, mu.hat, std.err, n.chains = 4, gibbs.samples = 5000) {
  
  tc.ccvx <- textConnection(ccvx.mod)

  model.init <- jags.model(tc.ccvx,
                           data = list('dose' = doses / max(doses),
                                       'eff' = mu.hat,
                                       'tau' = 1 / std.err^2,
                                       'pred.doses' = seq(0, 1, length.out = 250)),
                           n.chains = n.chains)
  close(tc.ccvx)
  
  # gibbs sampling
  ccvx.samples <- jags.samples(model.init, 
                               c("theta_0", "theta_1", "lambda", "mu.tilde", 
                                 "dose.post", "trt.post", "trt.post.dose"),
                               n.iter = gibbs.samples)
  
  # diagnostics with coda
  coda.samples <- coda.samples(model.init, c("theta_0", "theta_1", "lambda"), gibbs.samples)
  
  out <- list(ccvx.mod = ccvx.mod, jags.samples = ccvx.samples, coda.samples = coda.samples,
              doses = doses, mu.hat = mu.hat, std.err = std.err)
  out
}
